/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.vinuxproject.sonic;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int button=0x7f040004;
        public static final int buttonSkip=0x7f040005;
        public static final int pitch=0x7f040001;
        public static final int rate=0x7f040002;
        public static final int speed=0x7f040000;
        public static final int txtDuration=0x7f040006;
        public static final int txtPosition=0x7f040007;
        public static final int volume=0x7f040003;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int hello=0x7f030001;
    }
}
